## Group BY:
- permite agrupar por datos
- realizar operaciones agregadas: sum, promedio, 

## Estadisticos: 
- count()
- describe(): obtener los estadisticos
- sum()
- media(): suma de todos los valores /total
- median(): ordenar los valores y quedarte con el valor del medio
- max()
- std(): que tanto varian los datos con respecto a la media, es la raiz cuadrada de la varianza
- var(): varianza

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_csv('files/bank-additional_full.csv', index_col=0)
df.head()

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,empvarrate,conspriceidx,consconfidx,euribor3m,nremployed,y,date,latitude,longitude,contact_month,contact_year
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,married,basic 4y,0.0,0.0,0.0,telephone,261,1,999,0,nonexistent,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,agosto,2019.0
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,married,high school,NaN,0.0,0.0,telephone,149,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,septiembre,2016.0
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,married,high school,0.0,1.0,0.0,telephone,226,1,999,0,nonexistent,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,febrero,2019.0
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,married,basic 6y,0.0,0.0,0.0,telephone,151,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,noviembre,2015.0
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,married,high school,0.0,0.0,1.0,telephone,307,1,999,0,nonexistent,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,enero,2017.0

In [4]:
# cual es la media de edad de los clienest en funcion de su educacion 
resultado  = df.groupby('education')['age'].mean().reset_index()
resultado

             education        age
0             basic 4y  47.604900
1             basic 6y  40.418783
2             basic 9y  39.101327
3          high school  37.909434
4           illiterate  48.785714
5  professional course  39.994828
6    university degree  38.844152

In [6]:
df_education_describe  = df.groupby('education')['age'].agg(['mean', 'median', 'std', 'min', 'max']).reset_index()
df_education_describe

             education       mean  median        std   min   max
0             basic 4y  47.604900    47.0  12.261436  18.0  98.0
1             basic 6y  40.418783    39.0   8.680987  18.0  95.0
2             basic 9y  39.101327    38.0   9.604425  17.0  94.0
3          high school  37.909434    36.0   9.681421  18.0  88.0
4           illiterate  48.785714    45.0  11.709159  34.0  80.0
5  professional course  39.994828    38.0   9.869948  20.0  86.0
6    university degree  38.844152    36.0   9.626975  20.0  91.0

- la media de edad de basic 4y es 47 años. 
- la mediana de edad de basic 4y es 47 años. 
- la mayoria de los clientes  tienen edades está entre los 38 años y 65 años, aunque hay usaurios con 98 años y la persona mas joven tiene 18 años

2, 8, 2, 7, 4, 6, 6
 media  = 37/7 = 5,2 
 mediana es 6 
 2 2 4 6 6 7 8 

 2, 8, 2, 7, 4, 6, 6, 98, 80 (datos extremos == outliers)
 media  = 215/9 = 23,8   
 mediana es 6 
 2 2 4 6 6 7 8 80 98

 esto es salarios
media de 2500 euro
mediana es 1200

In [5]:
##  si los clientes que aceptan esta campaña son los mas jovenes
df_age_acept = df.groupby('y')['age'].mean().reset_index()
df_age_acept

# No hay diferencia entre las edaddes de quienes aceptan o no la campaña

     y        age
0   no  39.861724
1  yes  40.886310